Repository kenellorando/cadence, pull requests merged in 2020-01, with the labels that each got.

#163 Re-implement No. 2 Type B theme
  public/css/themes/No2TypeB.css
  public/index.html
  public/js/themeMetadata.js
Labels: UI

#166 Port improved search algorithm from v3 server
  server/database.go
  server/routes.go
Labels: enhancement

#167 Fix declaration of rows / variable names
  server/routes.go
Labels: bug

#169 Mobile UI improvements
  public/css/base.css
  public/css/modules/themeButton.css
  public/index.html
  public/js/themeChanger.js
Labels: UI

#171 Loop all given file extensions
  server/database.go
Labels: bug

#174 Return of the favicon
  public/404/index.html
  public/index.html
  public/static/favicon.ico
  server/main.go
Labels: UI
